@if($product->product_type == 'glasses')
<!--<a href="#collapseExample" class="btn btn-green" data-toggle="collapse">{{_i("Buy with perception")}}</a>-->
<div id="collapseExample" class="">
<!--    <div class="head-title"> {{_i("Do you have prescription")}}</div>
    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" checked id="yes" value="yes" name="radio_perception"  class="custom-control-input">
        <label class="custom-control-label" for="yes">{{_i("Yes")}}</label>
    </div>
    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio"  id="no" name="radio_perception" value="no"   class="custom-control-input">
        <label class="custom-control-label" for="no"> {{_i("No (we will contact you later)")}}</label>
    </div>-->
    <div id="div_glasses">
        <hr />
        <table class="table text-center table-borderless table-sm">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">S</th>
                    <th scope="col">CYL</th>
                    <th scope="col">A</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">R</th>
                    <td>
                        <select class="wide from-control rs" name="rs">
                            <option data-old="" value="">- {{_i("Select")}} -</option>
                            <option value="-14">-14 dpt</option>
                            <option value="-13.75">-13.75 dpt</option>
                            <option value="-13.5">-13.5 dpt</option>
                            <option value="-13.25">-13.25 dpt</option>
                            <option value="-13">-13 dpt</option>
                            <option value="-12.75">-12.75 dpt</option>
                            <option value="-12.50">-12.50 dpt</option>
                            <option value="-12.25">-12.25 dpt</option>
                            <option value="-12">-12 dpt</option>
                            <option value="-11.75">-11.75 dpt</option>
                            <option value="-11.5">-11.5 dpt</option>
                            <option value="-11.25">-11.25 dpt</option>
                            <option value="-11">-11 dpt</option>
                            <option value="-10.75">-10.75 dpt</option>
                            <option value="-10.5">-10.5 dpt</option>
                            <option value="-10.25">-10.25 dpt</option>
                            <option value="-10">-10 dpt</option>
                            <option value="-9.75">-9.75 dpt</option>
                            <option value="-9.5">-9.5 dpt</option>
                            <option value="-9.25">-9.25 dpt</option>
                            <option value="-9">-9 dpt</option>
                            <option value="-8.75">-8.75 dpt</option>
                            <option value="-8.5">-8.5 dpt</option>
                            <option value="-8.25">-8.25 dpt</option>
                            <option value="-8">-8 dpt</option>
                            <option value="-7.75">-7.75 dpt</option>
                            <option value="-7.5">-7.5 dpt</option>
                            <option value="-7.25">-7.25 dpt</option>
                            <option value="-7">-7 dpt</option>
                            <option value="-6.75">-6.75 dpt</option>
                            <option value="-6.5">-6.5 dpt</option>
                            <option value="-6.25">-6.25 dpt</option>
                            <option value="-6">-6 dpt</option>
                            <option value="-5.75">-5.75 dpt</option>
                            <option value="-5.5">-5.5 dpt</option>
                            <option value="-5.25">-5.25 dpt</option>
                            <option value="-5">-5 dpt</option>
                            <option value="-4.75">-4.75 dpt</option>
                            <option value="-4.5">-4.5 dpt</option>
                            <option value="-4.25">-4.25 dpt</option>
                            <option value="-4">-4 dpt</option>
                            <option value="-3.75">-3.75 dpt</option>
                            <option value="-3.5">-3.5 dpt</option>
                            <option value="-3.25">-3.25 dpt</option>
                            <option value="-3">-3 dpt</option>
                            <option value="-2.75">-2.75 dpt</option>
                            <option value="-2.5">-2.5 dpt</option>
                            <option value="-2.25">-2.25 dpt</option>
                            <option value="-2">-2 dpt</option>
                            <option value="-1.75">-1.75 dpt</option>
                            <option value="-1.5">-1.5 dpt</option>
                            <option value="-1.25">-1.25 dpt</option>
                            <option value="-1">-1 dpt</option>
                            <option value="-0.75">-0.75 dpt</option>
                            <option value="-0.5">-0.5 dpt</option>
                            <option value="-0.25">-0.25 dpt</option>
                            <option value="0.25">0.25 dpt</option>
                            <option value="0.5">0.5 dpt</option>
                            <option value="0.75">0.75 dpt</option>
                            <option value="1">1 dpt</option>
                            <option value="1.25">1.25 dpt</option>
                            <option value="1.5">1.5 dpt</option>
                            <option value="1.75">1.75 dpt</option>
                            <option value="2">2 dpt</option>
                            <option value="2.25">2.25 dpt</option>
                            <option value="2.5">2.5 dpt</option>
                            <option value="2.75">2.75 dpt</option>
                            <option value="3">3 dpt</option>
                            <option value="3.25">3.25 dpt</option>
                            <option value="3.5">3.5 dpt</option>
                            <option value="3.75">3.75 dpt</option>
                            <option value="4">4 dpt</option>
                            <option value="4.25">4.25 dpt</option>
                            <option value="4.5">4.5 dpt</option>
                            <option value="4.75">4.75 dpt</option>
                            <option value="5">5 dpt</option>
                            <option value="5.25">5.25 dpt</option>
                            <option value="5.5">5.5 dpt</option>
                            <option value="5.75">5.75 dpt</option>
                            <option value="6">6 dpt</option>
                            <option value="6.25">6.25 dpt</option>
                            <option value="6.5">6.5 dpt</option>
                            <option value="6.75">6.75 dpt</option>
                            <option value="7">7 dpt</option>
                            <option value="7.25">7.25 dpt</option>
                            <option value="7.5">7.5 dpt</option>
                            <option value="7.75">7.75 dpt</option>
                            <option value="8">8 dpt</option>
                            <option value="8.25">8.25 dpt</option>
                            <option value="8.5">8.5 dpt</option>
                            <option value="8.75">8.75 dpt</option>
                            <option value="9">9 dpt</option>
                            <option value="9.25">9.25 dpt</option>
                            <option value="9.5">9.5 dpt</option>
                            <option value="9.75">9.75 dpt</option>
                            <option value="10">10 dpt</option>
                            <option value="10.25">10.25 dpt</option>
                            <option value="10.5">10.5 dpt</option>
                            <option value="10.75">10.75 dpt</option>
                            <option value="11">11 dpt</option>
                            <option value="11.25">11.25 dpt</option>
                            <option value="11.5">11.5 dpt</option>
                            <option value="11.75">11.75 dpt</option>
                            <option value="12">12 dpt</option>
                        </select>
                    </td>
                    <td>
                        <select class="wide from-control rcyl" name="rcyl">
                            <option data-old="" value="">- {{_i("Select")}} -</option>
                            <option value="-6">-6 dpt</option>
                            <option value="-5.75">-5.75 dpt</option>
                            <option value="-5.5">-5.5 dpt</option>
                            <option value="-5.25">-5.25 dpt</option>
                            <option value="-5">-5 dpt</option>
                            <option value="-4.75">-4.75 dpt</option>
                            <option value="-4.5">-4.5 dpt</option>
                            <option value="-4.25">-4.25 dpt</option>
                            <option value="-4">-4 dpt</option>
                            <option value="-3.75">-3.75 dpt</option>
                            <option value="-3.5">-3.5 dpt</option>
                            <option value="-3.25">-3.25 dpt</option>
                            <option value="-3">-3 dpt</option>
                            <option value="-2.75">-2.75 dpt</option>
                            <option value="-2.5">-2.5 dpt</option>
                            <option value="-2.25">-2.25 dpt</option>
                            <option value="-2">-2 dpt</option>
                            <option value="-1.75">-1.75 dpt</option>
                            <option value="-1.5">-1.5 dpt</option>
                            <option value="-1.25">-1.25 dpt</option>
                            <option value="-1">-1 dpt</option>
                            <option value="-0.75">-0.75 dpt</option>
                            <option value="-0.5">-0.5 dpt</option>
                            <option value="-0.25">-0.25 dpt</option>
                            <option value="0.25">0.25 dpt</option>
                            <option value="0.5">0.5 dpt</option>
                            <option value="0.75">0.75 dpt</option>
                            <option value="1">1 dpt</option>
                            <option value="1.25">1.25 dpt</option>
                            <option value="1.5">1.5 dpt</option>
                            <option value="1.75">1.75 dpt</option>
                            <option value="2">2 dpt</option>
                            <option value="2.25">2.25 dpt</option>
                            <option value="2.5">2.5 dpt</option>
                            <option value="2.75">2.75 dpt</option>
                            <option value="3">3 dpt</option>
                            <option value="3.25">3.25 dpt</option>
                            <option value="3.5">3.5 dpt</option>
                            <option value="3.75">3.75 dpt</option>
                            <option value="4">4 dpt</option>
                            <option value="4.25">4.25 dpt</option>
                            <option value="4.5">4.5 dpt</option>
                            <option value="4.75">4.75 dpt</option>
                            <option value="5">5 dpt</option>
                            <option value="5.25">5.25 dpt</option>
                            <option value="5.5">5.5 dpt</option>
                            <option value="5.75">5.75 dpt</option>
                            <option value="6">6 dpt</option>
                            <option value="6.25">6.25 dpt</option>
                            <option value="6.5">6.5 dpt</option>
                            <option value="6.75">6.75 dpt</option>
                            <option value="7">7 dpt</option>
                            <option value="7.25">7.25 dpt</option>
                            <option value="7.5">7.5 dpt</option>
                            <option value="7.75">7.75 dpt</option>
                            <option value="8">8 dpt</option>
                        </select>
                    </td>
                    <td>
                        <select class="wide from-control ra" name="ra">
                            <option data-old="" value="">- {{_i("Select")}} -</option>
                            <option  value="0 deg">0 deg</option>
                            <option value="1 deg">1 deg</option>
                            <option value="2 deg">2 deg</option>
                            <option value="3 deg">3 deg</option>
                            <option value="4 deg">4 deg</option>
                            <option value="5 deg">5 deg</option>
                            <option value="6 deg">6 deg</option>
                            <option value="7 deg">7 deg</option>
                            <option value="8 deg">8 deg</option>
                            <option value="9 deg">9 deg</option>
                            <option value="10 deg">10 deg</option>
                            <option value="11 deg">11 deg</option>
                            <option value="12 deg">12 deg</option>
                            <option value="13 deg">13 deg</option>
                            <option value="14 deg">14 deg</option>
                            <option value="15 deg">15 deg</option>
                            <option value="16 deg">16 deg</option>
                            <option value="17 deg">17 deg</option>
                            <option value="18 deg">18 deg</option>
                            <option value="19 deg">19 deg</option>
                            <option value="20 deg">20 deg</option>
                            <option value="21 deg">21 deg</option>
                            <option value="22 deg">22 deg</option>
                            <option value="23 deg">23 deg</option>
                            <option value="24 deg">24 deg</option>
                            <option value="25 deg">25 deg</option>
                            <option value="26 deg">26 deg</option>
                            <option value="27 deg">27 deg</option>
                            <option value="28 deg">28 deg</option>
                            <option value="29 deg">29 deg</option>
                            <option value="30 deg">30 deg</option>
                            <option value="31 deg">31 deg</option>
                            <option value="32 deg">32 deg</option>
                            <option value="33 deg">33 deg</option>
                            <option value="34 deg">34 deg</option>
                            <option value="35 deg">35 deg</option>
                            <option value="36 deg">36 deg</option>
                            <option value="37 deg">37 deg</option>
                            <option value="38 deg">38 deg</option>
                            <option value="39 deg">39 deg</option>
                            <option value="40 deg">40 deg</option>
                            <option value="41 deg">41 deg</option>
                            <option value="42 deg">42 deg</option>
                            <option value="43 deg">43 deg</option>
                            <option value="44 deg">44 deg</option>
                            <option value="45 deg">45 deg</option>
                            <option value="46 deg">46 deg</option>
                            <option value="47 deg">47 deg</option>
                            <option value="48 deg">48 deg</option>
                            <option value="49 deg">49 deg</option>
                            <option value="50 deg">50 deg</option>
                            <option value="51 deg">51 deg</option>
                            <option value="52 deg">52 deg</option>
                            <option value="53 deg">53 deg</option>
                            <option value="54 deg">54 deg</option>
                            <option value="55 deg">55 deg</option>
                            <option value="56 deg">56 deg</option>
                            <option value="57 deg">57 deg</option>
                            <option value="58 deg">58 deg</option>
                            <option value="59 deg">59 deg</option>
                            <option value="60 deg">60 deg</option>
                            <option value="61 deg">61 deg</option>
                            <option value="62 deg">62 deg</option>
                            <option value="63 deg">63 deg</option>
                            <option value="64 deg">64 deg</option>
                            <option value="65 deg">65 deg</option>
                            <option value="66 deg">66 deg</option>
                            <option value="67 deg">67 deg</option>
                            <option value="68 deg">68 deg</option>
                            <option value="69 deg">69 deg</option>
                            <option value="70 deg">70 deg</option>
                            <option value="71 deg">71 deg</option>
                            <option value="72 deg">72 deg</option>
                            <option value="73 deg">73 deg</option>
                            <option value="74 deg">74 deg</option>
                            <option value="75 deg">75 deg</option>
                            <option value="76 deg">76 deg</option>
                            <option value="77 deg">77 deg</option>
                            <option value="78 deg">78 deg</option>
                            <option value="79 deg">79 deg</option>
                            <option value="80 deg">80 deg</option>
                            <option value="81 deg">81 deg</option>
                            <option value="82 deg">82 deg</option>
                            <option value="83 deg">83 deg</option>
                            <option value="84 deg">84 deg</option>
                            <option value="85 deg">85 deg</option>
                            <option value="86 deg">86 deg</option>
                            <option value="87 deg">87 deg</option>
                            <option value="88 deg">88 deg</option>
                            <option value="89 deg">89 deg</option>
                            <option value="90 deg">90 deg</option>
                            <option value="91 deg">91 deg</option>
                            <option value="92 deg">92 deg</option>
                            <option value="93 deg">93 deg</option>
                            <option value="94 deg">94 deg</option>
                            <option value="95 deg">95 deg</option>
                            <option value="96 deg">96 deg</option>
                            <option value="97 deg">97 deg</option>
                            <option value="98 deg">98 deg</option>
                            <option value="99 deg">99 deg</option>
                            <option value="100 deg">100 deg</option>
                            <option value="101 deg">101 deg</option>
                            <option value="102 deg">102 deg</option>
                            <option value="103 deg">103 deg</option>
                            <option value="104 deg">104 deg</option>
                            <option value="105 deg">105 deg</option>
                            <option value="106 deg">106 deg</option>
                            <option value="107 deg">107 deg</option>
                            <option value="108 deg">108 deg</option>
                            <option value="109 deg">109 deg</option>
                            <option value="110 deg">110 deg</option>
                            <option value="111 deg">111 deg</option>
                            <option value="112 deg">112 deg</option>
                            <option value="113 deg">113 deg</option>
                            <option value="114 deg">114 deg</option>
                            <option value="115 deg">115 deg</option>
                            <option value="116 deg">116 deg</option>
                            <option value="117 deg">117 deg</option>
                            <option value="118 deg">118 deg</option>
                            <option value="119 deg">119 deg</option>
                            <option value="120 deg">120 deg</option>
                            <option value="121 deg">121 deg</option>
                            <option value="122 deg">122 deg</option>
                            <option value="123 deg">123 deg</option>
                            <option value="124 deg">124 deg</option>
                            <option value="125 deg">125 deg</option>
                            <option value="126 deg">126 deg</option>
                            <option value="127 deg">127 deg</option>
                            <option value="128 deg">128 deg</option>
                            <option value="129 deg">129 deg</option>
                            <option value="130 deg">130 deg</option>
                            <option value="131 deg">131 deg</option>
                            <option value="132 deg">132 deg</option>
                            <option value="133 deg">133 deg</option>
                            <option value="134 deg">134 deg</option>
                            <option value="135 deg">135 deg</option>
                            <option value="136 deg">136 deg</option>
                            <option value="137 deg">137 deg</option>
                            <option value="138 deg">138 deg</option>
                            <option value="139 deg">139 deg</option>
                            <option value="140 deg">140 deg</option>
                            <option value="141 deg">141 deg</option>
                            <option value="142 deg">142 deg</option>
                            <option value="143 deg">143 deg</option>
                            <option value="144 deg">144 deg</option>
                            <option value="145 deg">145 deg</option>
                            <option value="146 deg">146 deg</option>
                            <option value="147 deg">147 deg</option>
                            <option value="148 deg">148 deg</option>
                            <option value="149 deg">149 deg</option>
                            <option value="150 deg">150 deg</option>
                            <option value="151 deg">151 deg</option>
                            <option value="152 deg">152 deg</option>
                            <option value="153 deg">153 deg</option>
                            <option value="154 deg">154 deg</option>
                            <option value="155 deg">155 deg</option>
                            <option value="156 deg">156 deg</option>
                            <option value="157 deg">157 deg</option>
                            <option value="158 deg">158 deg</option>
                            <option value="159 deg">159 deg</option>
                            <option value="160 deg">160 deg</option>
                            <option value="161 deg">161 deg</option>
                            <option value="162 deg">162 deg</option>
                            <option value="163 deg">163 deg</option>
                            <option value="164 deg">164 deg</option>
                            <option value="165 deg">165 deg</option>
                            <option value="166 deg">166 deg</option>
                            <option value="167 deg">167 deg</option>
                            <option value="168 deg">168 deg</option>
                            <option value="169 deg">169 deg</option>
                            <option value="170 deg">170 deg</option>
                            <option value="171 deg">171 deg</option>
                            <option value="172 deg">172 deg</option>
                            <option value="173 deg">173 deg</option>
                            <option value="174 deg">174 deg</option>
                            <option value="175 deg">175 deg</option>
                            <option value="176 deg">176 deg</option>
                            <option value="177 deg">177 deg</option>
                            <option value="178 deg">178 deg</option>
                            <option value="179 deg">179 deg</option>
                            <option value="180 deg">180 deg</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th scope="row">L</th>
                    <td>
                        <select class="wide from-control ls" name="ls">
                            <option data-old="" value="">- {{_i("Select")}} -</option>
                            <option value="-14">-14 dpt</option>
                            <option value="-13.75">-13.75 dpt</option>
                            <option value="-13.5">-13.5 dpt</option>
                            <option value="-13.25">-13.25 dpt</option>
                            <option value="-13">-13 dpt</option>
                            <option value="-12.75">-12.75 dpt</option>
                            <option value="-12.50">-12.50 dpt</option>
                            <option value="-12.25">-12.25 dpt</option>
                            <option value="-12">-12 dpt</option>
                            <option value="-11.75">-11.75 dpt</option>
                            <option value="-11.5">-11.5 dpt</option>
                            <option value="-11.25">-11.25 dpt</option>
                            <option value="-11">-11 dpt</option>
                            <option value="-10.75">-10.75 dpt</option>
                            <option value="-10.5">-10.5 dpt</option>
                            <option value="-10.25">-10.25 dpt</option>
                            <option value="-10">-10 dpt</option>
                            <option value="-9.75">-9.75 dpt</option>
                            <option value="-9.5">-9.5 dpt</option>
                            <option value="-9.25">-9.25 dpt</option>
                            <option value="-9">-9 dpt</option>
                            <option value="-8.75">-8.75 dpt</option>
                            <option value="-8.5">-8.5 dpt</option>
                            <option value="-8.25">-8.25 dpt</option>
                            <option value="-8">-8 dpt</option>
                            <option value="-7.75">-7.75 dpt</option>
                            <option value="-7.5">-7.5 dpt</option>
                            <option value="-7.25">-7.25 dpt</option>
                            <option value="-7">-7 dpt</option>
                            <option value="-6.75">-6.75 dpt</option>
                            <option value="-6.5">-6.5 dpt</option>
                            <option value="-6.25">-6.25 dpt</option>
                            <option value="-6">-6 dpt</option>
                            <option value="-5.75">-5.75 dpt</option>
                            <option value="-5.5">-5.5 dpt</option>
                            <option value="-5.25">-5.25 dpt</option>
                            <option value="-5">-5 dpt</option>
                            <option value="-4.75">-4.75 dpt</option>
                            <option value="-4.5">-4.5 dpt</option>
                            <option value="-4.25">-4.25 dpt</option>
                            <option value="-4">-4 dpt</option>
                            <option value="-3.75">-3.75 dpt</option>
                            <option value="-3.5">-3.5 dpt</option>
                            <option value="-3.25">-3.25 dpt</option>
                            <option value="-3">-3 dpt</option>
                            <option value="-2.75">-2.75 dpt</option>
                            <option value="-2.5">-2.5 dpt</option>
                            <option value="-2.25">-2.25 dpt</option>
                            <option value="-2">-2 dpt</option>
                            <option value="-1.75">-1.75 dpt</option>
                            <option value="-1.5">-1.5 dpt</option>
                            <option value="-1.25">-1.25 dpt</option>
                            <option value="-1">-1 dpt</option>
                            <option value="-0.75">-0.75 dpt</option>
                            <option value="-0.5">-0.5 dpt</option>
                            <option value="-0.25">-0.25 dpt</option>
                            <option value="0.25">0.25 dpt</option>
                            <option value="0.5">0.5 dpt</option>
                            <option value="0.75">0.75 dpt</option>
                            <option value="1">1 dpt</option>
                            <option value="1.25">1.25 dpt</option>
                            <option value="1.5">1.5 dpt</option>
                            <option value="1.75">1.75 dpt</option>
                            <option value="2">2 dpt</option>
                            <option value="2.25">2.25 dpt</option>
                            <option value="2.5">2.5 dpt</option>
                            <option value="2.75">2.75 dpt</option>
                            <option value="3">3 dpt</option>
                            <option value="3.25">3.25 dpt</option>
                            <option value="3.5">3.5 dpt</option>
                            <option value="3.75">3.75 dpt</option>
                            <option value="4">4 dpt</option>
                            <option value="4.25">4.25 dpt</option>
                            <option value="4.5">4.5 dpt</option>
                            <option value="4.75">4.75 dpt</option>
                            <option value="5">5 dpt</option>
                            <option value="5.25">5.25 dpt</option>
                            <option value="5.5">5.5 dpt</option>
                            <option value="5.75">5.75 dpt</option>
                            <option value="6">6 dpt</option>
                            <option value="6.25">6.25 dpt</option>
                            <option value="6.5">6.5 dpt</option>
                            <option value="6.75">6.75 dpt</option>
                            <option value="7">7 dpt</option>
                            <option value="7.25">7.25 dpt</option>
                            <option value="7.5">7.5 dpt</option>
                            <option value="7.75">7.75 dpt</option>
                            <option value="8">8 dpt</option>
                            <option value="8.25">8.25 dpt</option>
                            <option value="8.5">8.5 dpt</option>
                            <option value="8.75">8.75 dpt</option>
                            <option value="9">9 dpt</option>
                            <option value="9.25">9.25 dpt</option>
                            <option value="9.5">9.5 dpt</option>
                            <option value="9.75">9.75 dpt</option>
                            <option value="10">10 dpt</option>
                            <option value="10.25">10.25 dpt</option>
                            <option value="10.5">10.5 dpt</option>
                            <option value="10.75">10.75 dpt</option>
                            <option value="11">11 dpt</option>
                            <option value="11.25">11.25 dpt</option>
                            <option value="11.5">11.5 dpt</option>
                            <option value="11.75">11.75 dpt</option>
                            <option value="12">12 dpt</option>
                        </select>
                    </td>
                    <td>
                        <select class="wide from-control lycl" name="lycl">
                            <option data-old="" value="">- {{_i("Select")}} -</option>
                            <option value="-6">-6 dpt</option>
                            <option value="-5.75">-5.75 dpt</option>
                            <option value="-5.5">-5.5 dpt</option>
                            <option value="-5.25">-5.25 dpt</option>
                            <option value="-5">-5 dpt</option>
                            <option value="-4.75">-4.75 dpt</option>
                            <option value="-4.5">-4.5 dpt</option>
                            <option value="-4.25">-4.25 dpt</option>
                            <option value="-4">-4 dpt</option>
                            <option value="-3.75">-3.75 dpt</option>
                            <option value="-3.5">-3.5 dpt</option>
                            <option value="-3.25">-3.25 dpt</option>
                            <option value="-3">-3 dpt</option>
                            <option value="-2.75">-2.75 dpt</option>
                            <option value="-2.5">-2.5 dpt</option>
                            <option value="-2.25">-2.25 dpt</option>
                            <option value="-2">-2 dpt</option>
                            <option value="-1.75">-1.75 dpt</option>
                            <option value="-1.5">-1.5 dpt</option>
                            <option value="-1.25">-1.25 dpt</option>
                            <option value="-1">-1 dpt</option>
                            <option value="-0.75">-0.75 dpt</option>
                            <option value="-0.5">-0.5 dpt</option>
                            <option value="-0.25">-0.25 dpt</option>
                            <option value="0.25">0.25 dpt</option>
                            <option value="0.5">0.5 dpt</option>
                            <option value="0.75">0.75 dpt</option>
                            <option value="1">1 dpt</option>
                            <option value="1.25">1.25 dpt</option>
                            <option value="1.5">1.5 dpt</option>
                            <option value="1.75">1.75 dpt</option>
                            <option value="2">2 dpt</option>
                            <option value="2.25">2.25 dpt</option>
                            <option value="2.5">2.5 dpt</option>
                            <option value="2.75">2.75 dpt</option>
                            <option value="3">3 dpt</option>
                            <option value="3.25">3.25 dpt</option>
                            <option value="3.5">3.5 dpt</option>
                            <option value="3.75">3.75 dpt</option>
                            <option value="4">4 dpt</option>
                            <option value="4.25">4.25 dpt</option>
                            <option value="4.5">4.5 dpt</option>
                            <option value="4.75">4.75 dpt</option>
                            <option value="5">5 dpt</option>
                            <option value="5.25">5.25 dpt</option>
                            <option value="5.5">5.5 dpt</option>
                            <option value="5.75">5.75 dpt</option>
                            <option value="6">6 dpt</option>
                            <option value="6.25">6.25 dpt</option>
                            <option value="6.5">6.5 dpt</option>
                            <option value="6.75">6.75 dpt</option>
                            <option value="7">7 dpt</option>
                            <option value="7.25">7.25 dpt</option>
                            <option value="7.5">7.5 dpt</option>
                            <option value="7.75">7.75 dpt</option>
                            <option value="8">8 dpt</option>
                        </select>
                    </td>
                    <td>
                        <select class="wide from-control la" name="la">
                            <option data-old="" value="">- {{_i("Select")}} -</option>
                            <option  value="0 deg">0 deg</option >
                            <option value="1 deg">1 deg</option>
                            <option value="2 deg">2 deg</option>
                            <option value="3 deg">3 deg</option>
                            <option value="4 deg">4 deg</option>
                            <option value="5 deg">5 deg</option>
                            <option value="6 deg">6 deg</option>
                            <option value="7 deg">7 deg</option>
                            <option value="8 deg">8 deg</option>
                            <option value="9 deg">9 deg</option>
                            <option value="10 deg">10 deg</option>
                            <option value="11 deg">11 deg</option>
                            <option value="12 deg">12 deg</option>
                            <option value="13 deg">13 deg</option>
                            <option value="14 deg">14 deg</option>
                            <option value="15 deg">15 deg</option>
                            <option value="16 deg">16 deg</option>
                            <option value="17 deg">17 deg</option>
                            <option value="18 deg">18 deg</option>
                            <option value="19 deg">19 deg</option>
                            <option value="20 deg">20 deg</option>
                            <option value="21 deg">21 deg</option>
                            <option value="22 deg">22 deg</option>
                            <option value="23 deg">23 deg</option>
                            <option value="24 deg">24 deg</option>
                            <option value="25 deg">25 deg</option>
                            <option value="26 deg">26 deg</option>
                            <option value="27 deg">27 deg</option>
                            <option value="28 deg">28 deg</option>
                            <option value="29 deg">29 deg</option>
                            <option value="30 deg">30 deg</option>
                            <option value="31 deg">31 deg</option>
                            <option value="32 deg">32 deg</option>
                            <option value="33 deg">33 deg</option>
                            <option value="34 deg">34 deg</option>
                            <option value="35 deg">35 deg</option>
                            <option value="36 deg">36 deg</option>
                            <option value="37 deg">37 deg</option>
                            <option value="38 deg">38 deg</option>
                            <option value="39 deg">39 deg</option>
                            <option value="40 deg">40 deg</option>
                            <option value="41 deg">41 deg</option>
                            <option value="42 deg">42 deg</option>
                            <option value="43 deg">43 deg</option>
                            <option value="44 deg">44 deg</option>
                            <option value="45 deg">45 deg</option>
                            <option value="46 deg">46 deg</option>
                            <option value="47 deg">47 deg</option>
                            <option value="48 deg">48 deg</option>
                            <option value="49 deg">49 deg</option>
                            <option value="50 deg">50 deg</option>
                            <option value="51 deg">51 deg</option>
                            <option value="52 deg">52 deg</option>
                            <option value="53 deg">53 deg</option>
                            <option value="54 deg">54 deg</option>
                            <option value="55 deg">55 deg</option>
                            <option value="56 deg">56 deg</option>
                            <option value="57 deg">57 deg</option>
                            <option value="58 deg">58 deg</option>
                            <option value="59 deg">59 deg</option>
                            <option value="60 deg">60 deg</option>
                            <option value="61 deg">61 deg</option>
                            <option value="62 deg">62 deg</option>
                            <option value="63 deg">63 deg</option>
                            <option value="64 deg">64 deg</option>
                            <option value="65 deg">65 deg</option>
                            <option value="66 deg">66 deg</option>
                            <option value="67 deg">67 deg</option>
                            <option value="68 deg">68 deg</option>
                            <option value="69 deg">69 deg</option>
                            <option value="70 deg">70 deg</option>
                            <option value="71 deg">71 deg</option>
                            <option value="72 deg">72 deg</option>
                            <option value="73 deg">73 deg</option>
                            <option value="74 deg">74 deg</option>
                            <option value="75 deg">75 deg</option>
                            <option value="76 deg">76 deg</option>
                            <option value="77 deg">77 deg</option>
                            <option value="78 deg">78 deg</option>
                            <option value="79 deg">79 deg</option>
                            <option value="80 deg">80 deg</option>
                            <option value="81 deg">81 deg</option>
                            <option value="82 deg">82 deg</option>
                            <option value="83 deg">83 deg</option>
                            <option value="84 deg">84 deg</option>
                            <option value="85 deg">85 deg</option>
                            <option value="86 deg">86 deg</option>
                            <option value="87 deg">87 deg</option>
                            <option value="88 deg">88 deg</option>
                            <option value="89 deg">89 deg</option>
                            <option value="90 deg">90 deg</option>
                            <option value="91 deg">91 deg</option>
                            <option value="92 deg">92 deg</option>
                            <option value="93 deg">93 deg</option>
                            <option value="94 deg">94 deg</option>
                            <option value="95 deg">95 deg</option>
                            <option value="96 deg">96 deg</option>
                            <option value="97 deg">97 deg</option>
                            <option value="98 deg">98 deg</option>
                            <option value="99 deg">99 deg</option>
                            <option value="100 deg">100 deg</option>
                            <option value="101 deg">101 deg</option>
                            <option value="102 deg">102 deg</option>
                            <option value="103 deg">103 deg</option>
                            <option value="104 deg">104 deg</option>
                            <option value="105 deg">105 deg</option>
                            <option value="106 deg">106 deg</option>
                            <option value="107 deg">107 deg</option>
                            <option value="108 deg">108 deg</option>
                            <option value="109 deg">109 deg</option>
                            <option value="110 deg">110 deg</option>
                            <option value="111 deg">111 deg</option>
                            <option value="112 deg">112 deg</option>
                            <option value="113 deg">113 deg</option>
                            <option value="114 deg">114 deg</option>
                            <option value="115 deg">115 deg</option>
                            <option value="116 deg">116 deg</option>
                            <option value="117 deg">117 deg</option>
                            <option value="118 deg">118 deg</option>
                            <option value="119 deg">119 deg</option>
                            <option value="120 deg">120 deg</option>
                            <option value="121 deg">121 deg</option>
                            <option value="122 deg">122 deg</option>
                            <option value="123 deg">123 deg</option>
                            <option value="124 deg">124 deg</option>
                            <option value="125 deg">125 deg</option>
                            <option value="126 deg">126 deg</option>
                            <option value="127 deg">127 deg</option>
                            <option value="128 deg">128 deg</option>
                            <option value="129 deg">129 deg</option>
                            <option value="130 deg">130 deg</option>
                            <option value="131 deg">131 deg</option>
                            <option value="132 deg">132 deg</option>
                            <option value="133 deg">133 deg</option>
                            <option value="134 deg">134 deg</option>
                            <option value="135 deg">135 deg</option>
                            <option value="136 deg">136 deg</option>
                            <option value="137 deg">137 deg</option>
                            <option value="138 deg">138 deg</option>
                            <option value="139 deg">139 deg</option>
                            <option value="140 deg">140 deg</option>
                            <option value="141 deg">141 deg</option>
                            <option value="142 deg">142 deg</option>
                            <option value="143 deg">143 deg</option>
                            <option value="144 deg">144 deg</option>
                            <option value="145 deg">145 deg</option>
                            <option value="146 deg">146 deg</option>
                            <option value="147 deg">147 deg</option>
                            <option value="148 deg">148 deg</option>
                            <option value="149 deg">149 deg</option>
                            <option value="150 deg">150 deg</option>
                            <option value="151 deg">151 deg</option>
                            <option value="152 deg">152 deg</option>
                            <option value="153 deg">153 deg</option>
                            <option value="154 deg">154 deg</option>
                            <option value="155 deg">155 deg</option>
                            <option value="156 deg">156 deg</option>
                            <option value="157 deg">157 deg</option>
                            <option value="158 deg">158 deg</option>
                            <option value="159 deg">159 deg</option>
                            <option value="160 deg">160 deg</option>
                            <option value="161 deg">161 deg</option>
                            <option value="162 deg">162 deg</option>
                            <option value="163 deg">163 deg</option>
                            <option value="164 deg">164 deg</option>
                            <option value="165 deg">165 deg</option>
                            <option value="166 deg">166 deg</option>
                            <option value="167 deg">167 deg</option>
                            <option value="168 deg">168 deg</option>
                            <option value="169 deg">169 deg</option>
                            <option value="170 deg">170 deg</option>
                            <option value="171 deg">171 deg</option>
                            <option value="172 deg">172 deg</option>
                            <option value="173 deg">173 deg</option>
                            <option value="174 deg">174 deg</option>
                            <option value="175 deg">175 deg</option>
                            <option value="176 deg">176 deg</option>
                            <option value="177 deg">177 deg</option>
                            <option value="178 deg">178 deg</option>
                            <option value="179 deg">179 deg</option>
                            <option value="180 deg">180 deg</option>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="head-title">{{_i("PD value")}}</div>
        <select class="float-none pd" name="pd">
            <option value=""> -- {{ _i('Choose PD') }} -- </option>
            <option value="25">25</option>
            <option value="26">26</option>
            <option value="27">27</option>
            <option value="28">28</option>
            <option value="29">29</option>
            <option value="30">30</option>
            <option value="31">31</option>
            <option value="32">32</option>
            <option value="33">33</option>
            <option value="34">34</option>
            <option value="35">35</option>
            <option value="36">36</option>
            <option value="37">37</option>
            <option value="38">38</option>
            <option value="39">39</option>
            <option value="40">40</option>
            <option value="41">41</option>
            <option value="42">42</option>
            <option value="43">43</option>
            <option value="44">44</option>
            <option value="45">45</option>
            <option value="46">46</option>
            <option value="47">47</option>
            <option value="48">48</option>
            <option value="49">49</option>
            <option value="50">50</option>
            <option value="51">51</option>
            <option value="52">52</option>
            <option value="53">53</option>
            <option value="54">54</option>
            <option value="55">55</option>
            <option value="56">56</option>
            <option value="57">57</option>
            <option value="58">58</option>
            <option value="59">59</option>
            <option value="60">60</option>
            <option value="61">61</option>
            <option value="62">62</option>
            <option value="63">63</option>
            <option value="64">64</option>
            <option value="65">65</option>
            <option value="66">66</option>
            <option value="67">67</option>
            <option value="68">68</option>
            <option value="69">69</option>
            <option value="70">70</option>
            <option value="71">71</option>
            <option value="72">72</option>
            <option value="73">73</option>
            <option value="74">74</option>
            <option value="75">75</option>
            <option value="76">76</option>
            <option value="78">78</option>
            <option value="79">79</option>
            <option value="80">80</option>
        </select>
        @if(count($productLenses) > 0)
            <hr>
            <div class="head-title">{{_i("Lenses")}}</div>

            @foreach ($productLenses as $option)
                <div class="custom-control custom-radio">
                    <input type="radio" id="{{$option->id}}"  value="{{$option->price}}" name="glasses_lens"  class="custom-control-input glasses_lens">
                    <label class="custom-control-label d-flex" for="{{$option->id}}">
                        {{$option->name}}

                        <strong class="price-per-piece">+ {{$option->price}} {{ $convert->code }}</strong>
                    </label>
                    <label class="control-label d-flex"><strong> {{$option->description}}</strong> </label>
                    <img src="{{url('uploads/'.$option->image)}}" class="img-fluid ">
                </div>
            @endforeach
        @endif

        <hr class="rule">

        <div class="mt-1">
            <a href="javascript:void(0)" class="addcart btn btn-blue my-1" id="button-cart">
                <input type="hidden" class="product_id" value="{{ $product->id }}" name="product_id">
                <input type="hidden" class="max_count" value="{{ $product->quantity }}" name="max_count">
                <input type="hidden" class="product_type" value="{{ $product->product_type }}" name="product_type">
                {{_i("Add To Cart")}}
            </a>
        </div>
{{--        <button type="submit" class="btn btn-blue my-1" data-loading-text="Loading..."  id="button-cart"> {{_i("Add To Cart")}}</button>--}}
    </div>
</div>

    @endif
